#include QMK_KEYBOARD_H
#include "features/caps_word.h"
#ifdef USE_SENSITIVE_INFO_SAMPLE
#   include "sensitive_info_sample.h"
#else
#   include "sensitive_info.h"
#endif


const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
	/*
	keymaps generated by `keymapviz -t fancy -k ergodash_2u_inner -c keymapviz.conf keymap.c`
	Note that LAYR_ keycodes below are macros defined in config.h as they are reused in caps_word.c, etc.
	*/

	/* Qwerty
	 * ┌───────┬───────┬───────┬───────┬───────┬───────┐                   ┌───────┬───────┬───────┬───────┬───────┬───────┐
	 * │  ESC  │   1   │   2   │   3   │   4   │   5   ├───────┐   ┌───────┤   6   │   7   │   8   │   9   │   0   │  - _  │
	 * ├───────┼───────┼───────┼───────┼───────┼───────┤ HOME  │   │ PG UP ├───────┼───────┼───────┼───────┼───────┼───────┤
	 * │  ` ~  │   Q   │   W   │   E   │   R   │   T   ├───────┤   ├───────┤   Y   │   U   │   I   │   O   │   P   │  \ |  │
	 * ├───────┼───────┼───────┼───────┼───────┼───────┤  END  │   │ PG DN ├───────┼───────┼───────┼───────┼───────┼───────┤
	 * │  TAB  │   A   │   S   │   D   │   F   │   G   ├───────┤   ├───────┤   H   │   J   │   K   │   L   │  ; :  │  ' "  │
	 * ├───────┼───────┼───────┼───────┼───────┼───────┤   [   │   │   ]   ├───────┼───────┼───────┼───────┼───────┼───────┤
	 * │ SHIFT │   Z   │   X   │   C   │   V   │   B   ├───────┘   └───────┤   N   │   M   │  , >  │  . <  │  / ?  │ SHIFT │
	 * ├───────┼───────┼───────┼───────┼───────┴───────┘                   └───────┴───────┼───────┼───────┼───────┼───────┤
	 * │ CTRL  │  GUI  │OSL=FN │  ALT  │       ┌───────┬───────┐   ┌───────┬───────┐       │ LEFT  │ DOWN  │  UP   │ RIGHT │
	 * └───────┴───────┴───────┴───────┘       │       │  DEL  │   │ LEAD  │       │       └───────┴───────┴───────┴───────┘
	 *                                 ┌───────┤ BKSPC ├───────┤   ├───────┤  SPC  ├───────┐
	 *                                 │ CTRL  │       │OSL=SYM│   │ ENTER │       │TT=NUM │
	 *                                 └───────┴───────┴───────┘   └───────┴───────┴───────┘                              */
	[_QWERTY] = LAYOUT_4key_2u_inner(\
	KC_ESC,	  KC_1,	    KC_2,     KC_3,     KC_4,     KC_5,     KC_HOME,        KC_PGUP,  KC_6,     KC_7,     KC_8,     KC_9,     KC_0,     KC_MINS, \
	KC_GRV,   KC_Q,	    KC_W,     KC_E,     KC_R,     KC_T,     KC_END,         KC_PGDN,  KC_Y,     KC_U,     KC_I,     KC_O,     KC_P,     KC_BSLS, \
	KC_TAB,   KC_A,	    KC_S,     KC_D,     KC_F,     KC_G,     KC_LBRC,        KC_RBRC,  KC_H,     KC_J,     KC_K,     KC_L,     KC_SCLN,  KC_QUOT, \
	KC_LSFT,  KC_Z,	    KC_X,     KC_C,     KC_V,     KC_B,     KC_DEL,         KC_LEAD,  KC_N,     KC_M,     KC_COMM,  KC_DOT,   KC_SLSH,  KC_RSFT, \
	KC_LCTL,  KC_LGUI,  LAYR_FN,  KC_LALT,  KC_LCTL,  KC_BSPC,  LAYR_SYM,       KC_ENT,   KC_SPC,   LAYR_NUM, KC_LEFT,  KC_DOWN,  KC_UP,    KC_RGHT  \
	),


	/* Number Pad
	 * ┌───────┬───────┬───────┬───────┬───────┬───────┐                   ┌───────┬───────┬───────┬───────┬───────┬───────┐
	 * │  ...  │       │       │       │       │       ├───────┐   ┌───────┤       │       │   /   │   *   │   -   │       │
	 * ├───────┼───────┼───────┼───────┼───────┼───────┤  ...  │   │  ...  ├───────┼───────┼───────┼───────┼───────┼───────┤
	 * │       │       │ HOME  │  UP   │  END  │ PG UP ├───────┤   ├───────┤   %   │   7   │   8   │   9   │   -   │       │
	 * ├───────┼───────┼───────┼───────┼───────┼───────┤  ...  │   │  ...  ├───────┼───────┼───────┼───────┼───────┼───────┤
	 * │  ...  │       │ LEFT  │ DOWN  │ RIGHT │ PG DN ├───────┤   ├───────┤  = +  │   4   │   5   │   6   │   +   │       │
	 * ├───────┼───────┼───────┼───────┼───────┼───────┤       │   │       ├───────┼───────┼───────┼───────┼───────┼───────┤
	 * │  ...  │       │       │       │       │       ├───────┘   └───────┤   $   │   1   │   2   │   3   │ ENTER │  ...  │
	 * ├───────┼───────┼───────┼───────┼───────┴───────┘                   └───────┴───────┼───────┼───────┼───────┼───────┤
	 * │  ...  │  ...  │  ...  │  ...  │       ┌───────┬───────┐   ┌───────┬───────┐       │   0   │   .   │       │       │
	 * └───────┴───────┴───────┴───────┘       │       │  ...  │   │  ...  │       │       └───────┴───────┴───────┴───────┘
	 *                                 ┌───────┤  ...  ├───────┤   ├───────┤   0   ├───────┐
	 *                                 │  ...  │       │  ...  │   │  ...  │       │  ...  │
	 *                                 └───────┴───────┴───────┘   └───────┴───────┴───────┘                              */
	[_NUM] = LAYOUT_4key_2u_inner(\
	KC_TRNS,  KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_TRNS,        KC_TRNS,  KC_NO,    KC_NO,    KC_PSLS,  KC_PAST,  KC_PMNS,  KC_NO,   \
	KC_NO,    KC_NO,   	KC_HOME,  KC_UP,    KC_END,   KC_PGUP,  KC_TRNS,        KC_TRNS,  KC_PERC,  KC_7,     KC_8,     KC_9,     KC_PMNS,  KC_NO,   \
	KC_TRNS,  KC_NO,    KC_LEFT,  KC_DOWN, 	KC_RGHT,  KC_PGDN,  KC_NO,          KC_NO,    KC_EQL,   KC_4,     KC_5,     KC_6,     KC_PPLS,  KC_NO,   \
	KC_TRNS,  KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_TRNS,        KC_TRNS,  KC_DLR,   KC_1,     KC_2,     KC_3,     KC_PENT,  KC_TRNS, \
	KC_TRNS,  KC_TRNS,  KC_TRNS,  KC_TRNS,  KC_TRNS,  KC_TRNS,  KC_TRNS,        KC_TRNS,  KC_0,     KC_TRNS,  KC_0,     KC_PDOT,  KC_NO,    KC_NO    \
	),


	/* Symbol Layer
	 * ┌───────┬───────┬───────┬───────┬───────┬───────┐                   ┌───────┬───────┬───────┬───────┬───────┬───────┐
	 * │  ...  │   !   │   @   │   #   │   $   │   %   ├───────┐   ┌───────┤   ^   │   &   │   *   │   (   │   )   │ [ _ ] │
	 * ├───────┼───────┼───────┼───────┼───────┼───────┤  ...  │   │  ...  ├───────┼───────┼───────┼───────┼───────┼───────┤
	 * │       │  ` ~  │   ~   │   {   │   }   │   ^   ├───────┤   ├───────┤   %   │   (   │   )   │ [ _ ] │  - _  │   |   │
	 * ├───────┼───────┼───────┼───────┼───────┼───────┤  ...  │   │  ...  ├───────┼───────┼───────┼───────┼───────┼───────┤
	 * │  ...  │   !   │   @   │   #   │   $   │   %   ├───────┤   ├───────┤  = +  │   &   │   *   │  - _  │   +   │  ` ~  │
	 * ├───────┼───────┼───────┼───────┼───────┼───────┤   {   │   │   }   ├───────┼───────┼───────┼───────┼───────┼───────┤
	 * │  ...  │       │       │   [   │   ]   │       ├───────┘   └───────┤   $   │   ^   │   <   │   >   │   ?   │  ...  │
	 * ├───────┼───────┼───────┼───────┼───────┴───────┘                   └───────┴───────┼───────┼───────┼───────┼───────┤
	 * │  ...  │  ...  │  ...  │  ...  │       ┌───────┬───────┐   ┌───────┬───────┐       │  ...  │  ...  │  ...  │  ...  │
	 * └───────┴───────┴───────┴───────┘       │       │  ...  │   │  ...  │       │       └───────┴───────┴───────┴───────┘
	 *                                 ┌───────┤  ...  ├───────┤   ├───────┤ [ _ ] ├───────┐
	 *                                 │  ...  │       │  ...  │   │  ...  │       │  ...  │
	 *                                 └───────┴───────┴───────┘   └───────┴───────┴───────┘                              */
	[_SYM] = LAYOUT_4key_2u_inner(\
	KC_TRNS,  KC_EXLM,  KC_AT,    KC_HASH,  KC_DLR,   KC_PERC,  KC_TRNS,        KC_TRNS,  KC_CIRC,  KC_AMPR,  KC_ASTR,  KC_LPRN,  KC_RPRN,  KC_UNDS, \
	KC_NO,    KC_GRV,   KC_TILD,  KC_LCBR,  KC_RCBR,  KC_CIRC,  KC_TRNS,        KC_TRNS,  KC_PERC,  KC_LPRN,  KC_RPRN,  KC_UNDS,  KC_MINS,  KC_PIPE, \
	KC_TRNS,  KC_EXLM,  KC_AT,    KC_HASH,  KC_DLR,   KC_PERC,  KC_LCBR,        KC_RCBR,  KC_EQL,   KC_AMPR,  KC_ASTR,  KC_MINS,  KC_PLUS,  KC_GRV,  \
	KC_TRNS,  KC_NO,    KC_NO,    KC_LBRC,  KC_RBRC,  KC_NO,    KC_TRNS,        KC_TRNS,  KC_DLR,   KC_CIRC,  KC_LT,    KC_GT,    KC_QUES,  KC_TRNS, \
	KC_TRNS,  KC_TRNS,  KC_TRNS,  KC_TRNS,  KC_TRNS,  KC_TRNS,  KC_TRNS,        KC_TRNS,  KC_UNDS,  KC_TRNS,  KC_TRNS,  KC_TRNS,  KC_TRNS,  KC_TRNS  \
	),


	/* Function Layer
	 * ┌───────┬───────┬───────┬───────┬───────┬───────┐                   ┌───────┬───────┬───────┬───────┬───────┬───────┐
	 * │       │  F1   │  F2   │  F3   │  F4   │  F5   ├───────┐   ┌───────┤  F6   │  F7   │  F8   │  F9   │  F10  │  F11  │
	 * ├───────┼───────┼───────┼───────┼───────┼───────┤  ...  │   │  ...  ├───────┼───────┼───────┼───────┼───────┼───────┤
	 * │       │ RESET │       │       │ VOL+  │BRGHT+ ├───────┤   ├───────┤       │       │INSERT │       │PRNTSCR│  F12  │
	 * ├───────┼───────┼───────┼───────┼───────┼───────┤  ...  │   │  ...  ├───────┼───────┼───────┼───────┼───────┼───────┤
	 * │       │       │       │       │ VOL-  │BRGHT- ├───────┤   ├───────┤       │       │       │SCRNLCK│ PAUSE │       │
	 * ├───────┼───────┼───────┼───────┼───────┼───────┤       │   │       ├───────┼───────┼───────┼───────┼───────┼───────┤
	 * │  ...  │       │       │       │ MUTE  │       ├───────┘   └───────┤       │       │       │       │       │  ...  │
	 * ├───────┼───────┼───────┼───────┼───────┴───────┘                   └───────┴───────┼───────┼───────┼───────┼───────┤
	 * │  ...  │  ...  │  ...  │  ...  │       ┌───────┬───────┐   ┌───────┬───────┐       │  ...  │  ...  │  ...  │  ...  │
	 * └───────┴───────┴───────┴───────┘       │       │  ...  │   │  ...  │       │       └───────┴───────┴───────┴───────┘
	 *                                 ┌───────┤  ...  ├───────┤   ├───────┤  ...  ├───────┐
	 *                                 │  ...  │       │  ...  │   │  ...  │       │  ...  │
	 *                                 └───────┴───────┴───────┘   └───────┴───────┴───────┘                              */
	[_FN] = LAYOUT_4key_2u_inner(\
	KC_NO,    KC_F1,    KC_F2,    KC_F3,    KC_F4,    KC_F5,    KC_TRNS,        KC_TRNS,  KC_F6,    KC_F7,    KC_F8,    KC_F9,    KC_F10,   KC_F11,  \
	KC_NO,    RESET,    KC_NO,    KC_NO,    KC_VOLU,  KC_BRIU,  KC_TRNS,        KC_TRNS,  KC_NO,    KC_NO,    KC_INS,   KC_NO,    KC_PSCR,  KC_F12,  \
	KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_VOLD,  KC_BRID,  KC_NO,          KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_SLCK,  KC_PAUS,  KC_NO,   \
	KC_TRNS,  KC_NO,    KC_NO,    KC_NO,    KC_MUTE,  KC_NO,    KC_TRNS,        KC_TRNS,  KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_TRNS, \
	KC_TRNS,  KC_TRNS,  KC_TRNS,  KC_TRNS,  KC_TRNS,  KC_TRNS,  KC_TRNS,        KC_TRNS,  KC_TRNS,  KC_TRNS,  KC_TRNS,  KC_TRNS,  KC_TRNS,  KC_TRNS  \
	),


	/* Right-hand direction pad
	 * ┌───────┬───────┬───────┬───────┬───────┬───────┐                   ┌───────┬───────┬───────┬───────┬───────┬───────┐
	 * │       │       │       │       │       │       ├───────┐   ┌───────┤       │       │       │       │       │       │
	 * ├───────┼───────┼───────┼───────┼───────┼───────┤       │   │       ├───────┼───────┼───────┼───────┼───────┼───────┤
	 * │       │       │       │       │       │       ├───────┤   ├───────┤ PG UP │ HOME  │  UP   │  END  │       │       │
	 * ├───────┼───────┼───────┼───────┼───────┼───────┤       │   │       ├───────┼───────┼───────┼───────┼───────┼───────┤
	 * │       │       │       │       │       │       ├───────┤   ├───────┤ PG DN │ LEFT  │ DOWN  │ RIGHT │       │       │
	 * ├───────┼───────┼───────┼───────┼───────┼───────┤       │   │       ├───────┼───────┼───────┼───────┼───────┼───────┤
	 * │  ...  │       │       │       │       │       ├───────┘   └───────┤       │       │       │       │       │  ...  │
	 * ├───────┼───────┼───────┼───────┼───────┴───────┘                   └───────┴───────┼───────┼───────┼───────┼───────┤
	 * │  ...  │  ...  │  ...  │  ...  │       ┌───────┬───────┐   ┌───────┬───────┐       │  ...  │  ...  │  ...  │  ...  │
	 * └───────┴───────┴───────┴───────┘       │       │  ...  │   │  ...  │       │       └───────┴───────┴───────┴───────┘
	 *                                 ┌───────┤  ...  ├───────┤   ├───────┤  ...  ├───────┐
	 *                                 │  ...  │       │  ...  │   │  ...  │       │  ...  │
	 *                                 └───────┴───────┴───────┘   └───────┴───────┴───────┘                              */
	[_RHDIR] = LAYOUT_4key_2u_inner(\
	KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,          KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,   \
	KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,          KC_NO,    KC_PGUP,  KC_HOME,  KC_UP,    KC_END,   KC_NO,    KC_NO,   \
	KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,          KC_NO,    KC_PGDN,  KC_LEFT,  KC_DOWN,  KC_RGHT,  KC_NO,    KC_NO,   \
	KC_TRNS,  KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_TRNS,        KC_TRNS,  KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_TRNS, \
	KC_TRNS,  KC_TRNS,  KC_TRNS,  KC_TRNS,  KC_TRNS,  KC_TRNS,  KC_TRNS,        KC_TRNS,  KC_TRNS,  KC_TRNS,  KC_TRNS,  KC_TRNS,  KC_TRNS,  KC_TRNS  \
	)
};


void dynamic_macro_call( uint16_t action ) {
  dprintf("Processing dyn_macro_call(0x%04X)\n", action);

  keyrecord_t kr;
  kr.event.pressed = false;

  if ( action == DYN_REC_STOP ) {
    kr.event.pressed = true;
  }

  process_dynamic_macro( action, &kr );
}

void dynamic_macro_record_key_user(int8_t direction, keyrecord_t *record, bool success) {
  keypos_t key = record->event.key;
  uint16_t keycode = keymap_key_to_keycode(layer_switch_get_layer(key), key);
  
  if ( keycode == KC_LEAD ) {
    dprintf("Macro recording stopped due to KC_LEAD keycode.\n");
    dynamic_macro_call(DYN_REC_STOP);
  }
}


LEADER_EXTERNS();

void matrix_scan_user(void) {
  LEADER_DICTIONARY() {
    leading = false;
    leader_end();

    SEQ_ONE_KEY(KC_C) {
      SEND_STRING(SENSITIVE_DOMAIN_C);
    }
    SEQ_TWO_KEYS(KC_C, KC_C) {
      SEND_STRING(SENSITIVE_DOMAIN_CC);
    }
    SEQ_TWO_KEYS(KC_C, KC_L) {     // Caps lock
      tap_code(KC_CAPS);
    }
	SEQ_TWO_KEYS(KC_E, KC_G) {
      SEND_STRING(SENSITIVE_EMAIL_EG);
    }
	SEQ_TWO_KEYS(KC_E, KC_K) {
      SEND_STRING(SENSITIVE_EMAIL_EK);
    }
    SEQ_TWO_KEYS(KC_E, KC_S) {
      SEND_STRING(SENSITIVE_EMAIL_ES);
    }
    SEQ_TWO_KEYS(KC_E, KC_Y) {
      SEND_STRING(SENSITIVE_EMAIL_EY);
    }
    SEQ_ONE_KEY(KC_K) {
      SEND_STRING(SS_LCTRL(SS_LALT("a")));     // CTRL + ALT + a (Keepass)
    }
/* Dynamic Macros
      Note that the dynamic_macro_record_key_user() user hook sends DYN_REC_STOP when
	  KC_LEAD is pressed but the keyboard would still be in "leader key" mode, so the
	  M-R-S sequence provides a safe sequence/action to complete the "leader key" mode,
	  DYN_REC_STOP is sent a second time.
*/
	SEQ_TWO_KEYS(KC_M, KC_J) {
      dynamic_macro_call(DYN_MACRO_PLAY1);
    }
	SEQ_TWO_KEYS(KC_M, KC_K) {
      dynamic_macro_call(DYN_MACRO_PLAY2);
    }
	SEQ_THREE_KEYS(KC_M, KC_R, KC_J) {
      dynamic_macro_call(DYN_REC_START1);
    }
	SEQ_THREE_KEYS(KC_M, KC_R, KC_K) {
      dynamic_macro_call(DYN_REC_START2);
    }
	SEQ_THREE_KEYS(KC_M, KC_R, KC_S) {
      dynamic_macro_call(DYN_REC_STOP);
    }
//  End of dynamic macros
	SEQ_TWO_KEYS(KC_S, KC_G) {
      SEND_STRING(SENSITIVE_SIG_G);
    }
  }
};

bool process_record_user(uint16_t keycode, keyrecord_t *record) {
  dprintf("KL: kc: 0x%04X, col: %u, row: %u, pressed: %b, time: %u, interrupt: %b, count: %u\n", keycode, record->event.key.col, record->event.key.row, record->event.pressed, record->event.time, record->tap.interrupted, record->tap.count);
  
  if (!process_caps_word(keycode, record)) { return false; }
  
  switch (keycode) {
    case KC_F9:	//Just a simple case statement to catch F9 press
      if (record->event.pressed) {
        dprint("It's unlikely that F9 will be pressed.\n");
      }
      return false;
      break;
  }
  
  return true;
};
